apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: fullstack
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.servicePort }}
    targetPort: {{ .Values.backend.service.servicePort }}