apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels: 
    app: fullstack
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: fullstack
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
      - name: "{{ .Values.backend.image.repository }}"
        image: "{{ .Values.backend.image.repository }}/{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports: 
        - containerPort: {{ .Values.backend.service.servicePort}}
