apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: fullstack
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.servicePort }}
    targetPort: {{ .Values.frontend.service.servicePort }}