frontend:
  replicaCount: 1
  image:
    repository: martinsops 
    tag: frontend-app:v2.0
    pullPolicy: IfNotPresent
  service:
    name: frontend
    servicePort: 8000 # the port where nginx serves its traffic

backend:
  replicaCount: 1
  image:
    repository: martinsops 
    tag: backend-app:v2.1
    pullPolicy: IfNotPresent
  service:
    name: backend
    servicePort: 8080 # the port where nginx serves its traffic

